package fmt

// FieldType represents the abstract storage type of a struct field.
type FieldType int

const (
	FieldText FieldType = iota
	FieldInt
	FieldFloat
	FieldBool
	FieldBlob
)

// Field describes a single field in a struct's schema.
// It provides type metadata and constraint flags used by both
// database (orm) and UI (form) layers.
type Field struct {
	Name    string
	Type    FieldType
	PK      bool   // Primary Key
	Unique  bool
	NotNull bool
	AutoInc bool   // Auto-increment (numeric fields only)
	Input   string // UI hint: input type override ("email", "password", "-", etc.). Empty = auto.
}

var fieldTypeNames = []string{"text", "int", "float", "bool", "blob"}

func (ft FieldType) String() string {
	if int(ft) >= 0 && int(ft) < len(fieldTypeNames) {
		return fieldTypeNames[ft]
	}
	return "unknown"
}

// Fielder describes any type that can expose its schema, values, and
// writable pointers. It is the shared contract between orm (database)
// and form (UI) layers, replacing runtime reflection.
//
// Implementations are generated by ormc — never written by hand.
//
// Contract:
//   - Schema(), Values(), and Pointers() MUST return slices of the same length.
//   - The i-th element in each slice corresponds to the same struct field.
//   - Values() returns current field values for reading.
//   - Pointers() returns pointers to fields for writing (scan/sync).
type Fielder interface {
	Schema() []Field
	Values() []any
	Pointers() []any
}
