package fmt

// FieldType represents the abstract storage type of a struct field.
type FieldType int

const (
	FieldText   FieldType = iota // Any string
	FieldInt                     // Any integer
	FieldFloat                   // Any float
	FieldBool                    // Boolean
	FieldBlob                    // Binary data ([]byte)
	FieldStruct                  // Nested struct (implements Fielder)
)

// Field describes a single field in a struct's schema.
// It provides type metadata and constraint flags used by both
// database (orm) and UI (form) layers.
type Field struct {
	Name    string
	Type    FieldType
	PK      bool
	Unique  bool
	NotNull bool
	AutoInc bool
	Input   string // UI hint for form layer
	JSON    string // JSON key + modifiers ("email,omitempty"). Empty = use Field.Name as key.
}

var fieldTypeNames = []string{"text", "int", "float", "bool", "blob", "struct"}

func (ft FieldType) String() string {
	if int(ft) >= 0 && int(ft) < len(fieldTypeNames) {
		return fieldTypeNames[ft]
	}
	return "unknown"
}

// Fielder describes any type that can expose its schema and
// writable pointers. It is the shared contract between orm (database),
// form (UI), and json layers, replacing runtime reflection.
//
// Implementations are generated by code generators — never written by hand.
//
// Contract:
//   - Schema() and Pointers() MUST return slices of the same length.
//   - The i-th element in each slice corresponds to the same struct field.
//   - Pointers() returns pointers to fields for reading (dereference) and writing (scan/sync).
type Fielder interface {
	Schema() []Field
	Pointers() []any
}

// ReadValues reads field values through Pointers by dereferencing based on FieldType.
// Used by consumers that need []any (e.g., orm for SQL args).
// Hot-path consumers (json, form) should read through Pointers directly to avoid boxing.
func ReadValues(schema []Field, ptrs []any) []any {
	vals := make([]any, len(schema))
	for i, f := range schema {
		if ptrs[i] == nil {
			continue
		}
		switch f.Type {
		case FieldText:
			if p, ok := ptrs[i].(*string); ok && p != nil {
				vals[i] = *p
			}
		case FieldInt:
			switch p := ptrs[i].(type) {
			case *int64:
				if p != nil {
					vals[i] = *p
				}
			case *int:
				if p != nil {
					vals[i] = *p
				}
			case *int32:
				if p != nil {
					vals[i] = *p
				}
			case *uint:
				if p != nil {
					vals[i] = *p
				}
			case *uint32:
				if p != nil {
					vals[i] = *p
				}
			case *uint64:
				if p != nil {
					vals[i] = *p
				}
			}
		case FieldFloat:
			switch p := ptrs[i].(type) {
			case *float64:
				if p != nil {
					vals[i] = *p
				}
			case *float32:
				if p != nil {
					vals[i] = *p
				}
			}
		case FieldBool:
			if p, ok := ptrs[i].(*bool); ok && p != nil {
				vals[i] = *p
			}
		case FieldBlob:
			if p, ok := ptrs[i].(*[]byte); ok && p != nil {
				vals[i] = *p
			}
		case FieldStruct:
			vals[i] = ptrs[i] // pointer to nested struct IS the Fielder
		}
	}
	return vals
}

// ReadStringPtr reads a string from a typed pointer.
// Returns the string value and true if the pointer is *string, or ("", false) otherwise.
func ReadStringPtr(ptr any) (string, bool) {
	if p, ok := ptr.(*string); ok && p != nil {
		return *p, true
	}
	return "", false
}
