package fmt

// FieldType represents the abstract storage type of a struct field.
type FieldType int

const (
	FieldText     FieldType = iota // Any string
	FieldInt                       // Any integer
	FieldFloat                     // Any float
	FieldBool                      // Boolean
	FieldBlob                      // Binary data ([]byte)
	FieldStruct                    // Nested struct (implements Fielder)
	FieldIntSlice                  // []int
	FieldStructSlice               // []Fielder
)

var fieldTypeNames = []string{"text", "int", "float", "bool", "blob", "struct", "intslice", "structslice"}

// Widget is the contract for a semantic input type.
// It is implemented by tinywasm/form/input types and custom project inputs.
// Stored in Field.Widget; set by ormc code generation from the `input:` struct tag.
//
// Implementations must be stateless templates — Clone() returns a fresh copy
// for thread-safe use per request in the form layer.
//
// RenderHTML is intentionally excluded: rendering is a concern of tinywasm/form,
// not of the base schema package.
type Widget interface {
	Type() string                       // Semantic input type (e.g., "email", "textarea")
	Validate(value string) error        // Semantic validation for this input type
	Clone(parentID, name string) Widget // Returns a positioned instance; pass ("","") for a bare template
}

func (ft FieldType) String() string {
	if int(ft) >= 0 && int(ft) < len(fieldTypeNames) {
		return fieldTypeNames[ft]
	}
	return "unknown"
}

// FieldDB contains database-specific metadata.
// Extracted from Field to keep transport/UI structs lean.
type FieldDB struct {
	PK      bool
	Unique  bool
	AutoInc bool
}

// Field describes a single field in a struct's schema.
// It provides type metadata, constraint flags, and validation rules
// used by database (orm), transport (json), UI (form), and validation layers.
//
// Validation rules are embedded via Permitted. When a field has validation
// configured, Field.Validate(value) checks the value against all rules.
// Fields without validation rules pass any value.
type Field struct {
	Name      string
	Type      FieldType
	NotNull   bool
	OmitEmpty bool     // omit from JSON when zero value
	Widget    Widget   // ← NEW: set by ormc from `input:` tag. nil = no UI binding.
	DB        *FieldDB // nil for formonly/transport structs
	Permitted          // embedded: validation rules (characters, min/max)
}

// IsPK returns true if the field is a Primary Key.
func (f Field) IsPK() bool { return f.DB != nil && f.DB.PK }

// IsUnique returns true if the field has a Unique constraint.
func (f Field) IsUnique() bool { return f.DB != nil && f.DB.Unique }

// IsAutoInc returns true if the field is Auto-Increment.
func (f Field) IsAutoInc() bool { return f.DB != nil && f.DB.AutoInc }

// Validate checks a string value against this field's constraints.
// Checks NotNull first, then delegates to embedded Permitted.
func (f Field) Validate(value string) error {
	if f.NotNull && value == "" {
		return Err(f.Name, "required")
	}
	if value == "" {
		return nil // empty + not required = ok
	}
	if f.Widget != nil {
		if err := f.Widget.Validate(value); err != nil {
			return err
		}
	}
	// Only run Permitted validation if any rule is configured
	if f.hasPermittedRules() {
		return f.Permitted.Validate(f.Name, value)
	}
	return nil
}

// hasPermittedRules returns true if any Permitted field is non-zero.
func (f Field) hasPermittedRules() bool {
	return f.Letters || f.Tilde || f.Numbers || f.Spaces ||
		f.BreakLine || f.Tab || len(f.Extra) > 0 ||
		len(f.NotAllowed) > 0 || f.Minimum > 0 || f.Maximum > 0 ||
		f.StartWith != nil
}

// Fielder describes any type that can expose its schema and
// writable pointers. It is the shared contract between orm (database),
// form (UI), and json layers, replacing runtime reflection.
//
// Implementations are generated by code generators — never written by hand.
//
// Contract:
//   - Schema() and Pointers() MUST return slices of the same length.
//   - The i-th element in each slice corresponds to the same struct field.
//   - Pointers() returns pointers to fields for reading (dereference) and writing (scan/sync).
type Fielder interface {
	Schema() []Field
	Pointers() []any
}

// FielderSlice is implemented by generated code to allow
// iteration over a slice of structs without reflection.
type FielderSlice interface {
	Len() int
	At(i int) Fielder
	Append() Fielder
}

// Validator is implemented by types that can self-validate.
// Generated by ormc: func (m *X) Validate(action byte) error { return fmt.ValidateFields(action, m) }
// Used by form, json.Decode, and orm pre-insert to enforce data integrity.
type Validator interface {
	Validate(action byte) error
}

// Model describes a resource with a schema and a name.
// Standard interface used by DB, Form, and API layers.
type Model interface {
	Fielder
	ModelName() string
}

// SafeFields combines schema access with validation.
// Handlers that receive user input should accept SafeFields
// to enforce compile-time validation guarantees.
type SafeFields interface {
	Fielder
	Validator
}

// ValidateFields validates all fields of a Fielder based on the action ('c', 'u', 'd').
// For each FieldText field, reads the string value and calls Field.Validate.
// For non-text fields with NotNull, checks against zero value.
//
// This is the single validation entry point — ormc-generated Validate()
// methods call this function first.
func ValidateFields(action byte, f Fielder) error {
	schema := f.Schema()
	ptrs := f.Pointers()
	for i, field := range schema {
		// 'd' delete: only PK required, skip everything else
		if action == 'd' {
			if field.IsPK() {
				switch field.Type {
				case FieldText:
					val, _ := ReadStringPtr(ptrs[i])
					if val == "" {
						return Err(field.Name, "required")
					}
				default:
					if isZeroPtr(ptrs[i], field.Type) {
						return Err(field.Name, "required")
					}
				}
			}
			continue
		}

		// 'c' create: skip PK+AutoInc (DB assigns it)
		if action == 'c' && field.IsPK() && field.IsAutoInc() {
			continue
		}

		switch field.Type {
		case FieldText:
			val, _ := ReadStringPtr(ptrs[i])

			// PK always required (in 'c' without AutoInc, in 'u', and any other)
			if field.IsPK() && val == "" {
				return Err(field.Name, "required")
			}

			if err := field.Validate(val); err != nil {
				return err
			}

		case FieldStruct:
			// Recursive validation for nested structs
			if validator, ok := ptrs[i].(Validator); ok {
				if err := validator.Validate(action); err != nil {
					return err
				}
			} else if fielder, ok := ptrs[i].(Fielder); ok {
				if err := ValidateFields(action, fielder); err != nil {
					return err
				}
			}

		default:
			// PK always required
			if field.IsPK() && isZeroPtr(ptrs[i], field.Type) {
				return Err(field.Name, "required")
			}
			// Non-text fields: only check NotNull (zero value check)
			if field.NotNull && isZeroPtr(ptrs[i], field.Type) {
				return Err(field.Name, "required")
			}
		}
	}
	return nil
}

// isZeroPtr checks if a pointer points to a zero value.
func isZeroPtr(ptr any, ft FieldType) bool {
	switch ft {
	case FieldInt:
		switch p := ptr.(type) {
		case *int64:
			return *p == 0
		case *int:
			return *p == 0
		case *int32:
			return *p == 0
		case *uint:
			return *p == 0
		case *uint32:
			return *p == 0
		case *uint64:
			return *p == 0
		}
	case FieldFloat:
		switch p := ptr.(type) {
		case *float64:
			return *p == 0
		case *float32:
			return *p == 0
		}
	case FieldBool:
		if p, ok := ptr.(*bool); ok {
			return !*p
		}
	case FieldBlob:
		if p, ok := ptr.(*[]byte); ok {
			return len(*p) == 0
		}
	case FieldIntSlice:
		if p, ok := ptr.(*[]int); ok {
			return len(*p) == 0
		}
	case FieldStructSlice:
		// Since we handle various slice types and tinywasm avoids reflection,
		// we check for nil pointer or rely on the specific implementation to provide length.
		// For zero-check purposes, if it's a pointer to a slice, we check if it's nil.
		return ptr == nil
	}
	return false
}

// ReadValues reads field values through Pointers by dereferencing based on FieldType.
// Used by consumers that need []any (e.g., orm for SQL args).
// Hot-path consumers (json, form) should read through Pointers directly to avoid boxing.
func ReadValues(schema []Field, ptrs []any) []any {
	vals := make([]any, len(schema))
	for i, f := range schema {
		if ptrs[i] == nil {
			continue
		}
		switch f.Type {
		case FieldText:
			if p, ok := ptrs[i].(*string); ok && p != nil {
				vals[i] = *p
			}
		case FieldInt:
			switch p := ptrs[i].(type) {
			case *int64:
				if p != nil {
					vals[i] = *p
				}
			case *int:
				if p != nil {
					vals[i] = *p
				}
			case *int32:
				if p != nil {
					vals[i] = *p
				}
			case *uint:
				if p != nil {
					vals[i] = *p
				}
			case *uint32:
				if p != nil {
					vals[i] = *p
				}
			case *uint64:
				if p != nil {
					vals[i] = *p
				}
			}
		case FieldFloat:
			switch p := ptrs[i].(type) {
			case *float64:
				if p != nil {
					vals[i] = *p
				}
			case *float32:
				if p != nil {
					vals[i] = *p
				}
			}
		case FieldBool:
			if p, ok := ptrs[i].(*bool); ok && p != nil {
				vals[i] = *p
			}
		case FieldBlob:
			if p, ok := ptrs[i].(*[]byte); ok && p != nil {
				vals[i] = *p
			}
		case FieldStruct:
			vals[i] = ptrs[i] // pointer to nested struct IS the Fielder
		case FieldIntSlice:
			if p, ok := ptrs[i].(*[]int); ok && p != nil {
				vals[i] = *p
			}
		case FieldStructSlice:
			vals[i] = ptrs[i] // Pass the slice pointer as is
		}
	}
	return vals
}

// ReadStringPtr reads a string from a typed pointer.
// Returns the string value and true if the pointer is *string, or ("", false) otherwise.
func ReadStringPtr(ptr any) (string, bool) {
	if p, ok := ptr.(*string); ok && p != nil {
		return *p, true
	}
	return "", false
}
